# Generated by Django 5.1 on 2024-08-09 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='sans titre', max_length=100)),
                ('text', models.TextField()),
                ('photo', models.ImageField(upload_to='exercises/')),
                ('corrected', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='nom utilisateur', max_length=30)),
                ('first_name', models.CharField(default='prénom', max_length=30)),
                ('last_name', models.CharField(default='nom', max_length=30)),
                ('email', models.EmailField(default='email', max_length=254)),
                ('parent_first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('parent_last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('current_class', models.CharField(blank=True, choices=[('6e', '6e'), ('5e', '5e'), ('4e', '4e'), ('3e', '3e'), ('2de', '2de'), ('1ere', '1ere'), ('term', 'Terminale'), ('post_bac', 'Post Bac'), ('autre', 'Autre')], max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
