# Generated by Django 5.1 on 2024-08-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='photo',
        ),
        migrations.AddField(
            model_name='exercise',
            name='photo_answer',
            field=models.ImageField(blank=True, null=True, upload_to='exercises/answers/'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='photo_statement',
            field=models.ImageField(default='path/to/default/image.jpg', upload_to='exercises/statements/'),
        ),
    ]
