# Generated by Django 5.1 on 2024-08-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_exercise_photo_exercise_photo_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='photo_correction',
            field=models.ImageField(blank=True, null=True, upload_to='exercises/answers/'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='text_correction',
            field=models.CharField(default='pas de correction texte', max_length=500),
        ),
    ]
