# Generated by Django 5.1 on 2024-08-10 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_exercise_photo_correction_exercise_text_correction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='username',
        ),
        migrations.AddField(
            model_name='exercise',
            name='correction_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
