# Generated by Django 5.1 on 2024-08-10 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_userprofile_username_exercise_correction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='submission_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
