# Generated by Django 5.1 on 2024-08-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_userprofile_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='photo_correction',
            field=models.ImageField(blank=True, null=True, upload_to='exercises/corrections/'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='text_correction',
            field=models.CharField(default='pas de correction texte', max_length=800),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='title',
            field=models.CharField(default='sans titre', max_length=120),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='current_class',
            field=models.CharField(blank=True, choices=[('6e', '6e'), ('5e', '5e'), ('4e', '4e'), ('3e', '3e'), ('2de', '2de'), ('1ere', '1ere'), ('term', 'Terminale'), ('post_bac', 'Post Bac'), ('autre', 'Autre')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='parent_first_name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='parent_last_name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
