# Generated by Django 5.1 on 2024-08-13 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_exercise_corrected'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='audio_correction',
            field=models.FileField(blank=True, null=True, upload_to='exercises/audio_corrections/'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='corrected',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non'), ('En attente de modification', 'En attente de modification')], default='non', max_length=80, verbose_name='Corrigé'),
        ),
    ]
